# Generated by Django 2.0.7 on 2018-07-28 18:41

from django.db import migrations, models
import gti619_lab5.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[(gti619_lab5.core.models.Roles('Administrateur'), 'Administrateur'), (gti619_lab5.core.models.Roles('Clients Résidentiels'), 'Clients Résidentiels'), (gti619_lab5.core.models.Roles("Clients D'affaire"), "Clients D'affaire")], default=gti619_lab5.core.models.Roles('Administrateur'), max_length=5),
        ),
    ]
