# Generated by Django 2.0.7 on 2018-07-28 19:58

from django.db import migrations, models
import gti619_lab5.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180728_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[(gti619_lab5.core.models.Roles('Administrateur'), 'Administrateur'), (gti619_lab5.core.models.Roles('Clients Résidentiels'), 'Clients Résidentiels'), (gti619_lab5.core.models.Roles("Clients D'affaire"), "Clients D'affaire")], max_length=5),
        ),
    ]
