# Generated by Django 2.0.7 on 2018-07-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180728_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPeriodicChange', models.BooleanField(default=False)),
                ('pwdMinLength', models.PositiveIntegerField(default=8)),
                ('pwdMaxLength', models.PositiveIntegerField(blank=True, null=True)),
                ('mustHaveUppercase', models.BooleanField(default=False)),
                ('mustHaveLowercase', models.BooleanField(default=False)),
                ('mustHaveSpecialChar', models.BooleanField(default=False)),
                ('mustHaveNumericChar', models.BooleanField(default=False)),
                ('cannotUsePreviousPWD', models.BooleanField(default=False)),
                ('maxNumberAttemps', models.PositiveIntegerField(default=3)),
                ('delayBetweenAttemps', models.PositiveIntegerField(default=1)),
                ('contactAdminAfterFailure', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Administrateur', 'Administrateur'), ('Clients Résidentiels', 'Clients Résidentiels'), ("Clients D'affaire", "Clients D'affaire")], max_length=5),
        ),
    ]
